<?php
// Include Stripe PHP library
require_once('../init.php');

// Replace 'your_secret_key_here' with your actual secret key
\Stripe\Stripe::setApiKey('pk_test_51OoK4bSGoC3hK9NMtmcGSDnRv4DPyspgU7KZzhDDBsplJ7AT3ftqfl9lB1EKQqKBCbZL4bE4HU99aKEuCUFms6Li00Vk9GeoE8');

// Retrieve the token generated by the client-side script
$token = $_POST['stripeToken'];

// Set the total amount (in cents)
$total_amount = 2000; // Example: $20.00

try {
    // Create a charge
    $charge = \Stripe\Charge::create([
        'amount' => $total_amount,
        'currency' => 'usd',
        'description' => 'Example Charge',
        'source' => $token,
    ]);

    // Payment successful, do something here (e.g., update database, send email, etc.)

    // Redirect to a success page
    header("Location: payment_success.php");
    exit;
} catch (\Stripe\Exception\CardException $e) {
    // Card was declined
    $error = $e->getError()->message;
} catch (\Stripe\Exception\RateLimitException $e) {
    // Too many requests made to the API too quickly
    $error = "Too many requests. Please try again later.";
} catch (\Stripe\Exception\InvalidRequestException $e) {
    // Invalid parameters were supplied to Stripe's API
    $error = $e->getError()->message;
} catch (\Stripe\Exception\AuthenticationException $e) {
    // Authentication with Stripe's API failed
    $error = "Authentication failed. Please try again later.";
} catch (\Stripe\Exception\ApiConnectionException $e) {
    // Network communication with Stripe failed
    $error = "Network error. Please try again later.";
} catch (\Stripe\Exception\ApiErrorException $e) {
    // Generic error occurred
    $error = "An error occurred. Please try again later.";
}

// Redirect to an error page with the error message
header("Location: payment_error.php?error=" . urlencode($error));
exit;
?>
